name: Bot Docker Build, Push & GitHub Release

on:
  push:
    branches:
      - tg_bot  # Запускаем только при изменениях в ветке бота

permissions:
  contents: write  # Даем права на создание релизов

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Загружаем все коммиты

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create .env file
        run: |
          echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" > .env

      - name: Build and Push Bot Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/electro_bot:latest -f Dockerfile .
          docker push $DOCKER_USERNAME/electro_bot:latest

      - name: Archive Source Code
        run: zip -r bot-release.zip . -x ".git/*"

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bot-package
          path: bot-release.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: bot-v1.0.${{ github.run_number }}
          name: Bot_Release v1.0.${{ github.run_number }}
          body: "Автоматически созданный релиз для бота."
          draft: false
          prerelease: false
          files: bot-release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
