name: Bot Test, Build & Deploy

on:
  push:
    branches:
      - tg_bot

permissions:
  contents: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_USERNAME: ${{ secrets.TELEGRAM_USERNAME }}

jobs:
  test-and-deploy-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Bot repository
        uses: actions/checkout@v3
        with:
          path: bot

      - name: Checkout API repository (for tests)
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: API
          path: api

      - name: Debug - List repo contents
        run: ls -R

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Create test docker-compose.yml
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          networks:
            custom_network:
              driver: bridge
          services:
            api:
              build: ./api
              container_name: electro_api
              restart: always
              ports:
                - "8375:8375"
              environment:
                - FLASK_ENV=production
              networks:
                - custom_network

            bot:
              build: ./bot
              container_name: electro_bot
              restart: always
              ports:
                - "8374:8374"
              environment:
                - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
                - TELEGRAM_USERNAME=${TELEGRAM_USERNAME}
              networks:
                - custom_network
          EOF

      - name: Build Bot Image
        run: docker build -t electro_bot:test -f bot/Dockerfile ./bot

      - name: Build API Image (for testing)
        run: docker build -t electro_api:test -f api/Dockerfile ./api

      - name: Run Services for Testing
        run: docker-compose up -d

      - name: Wait for services to start
        run: sleep 10

      - name: Send Test Request to API
        run: |
          curl -X POST http://api:8375/new_request \
          -H "Content-Type: application/json" \
          -d '{"name": "Test User", "phoneNumber": "1234567890", "TypeOFService": "Test Service"}'

      - name: Check Telegram Message
        run: |
          sleep 5
          RESPONSE=$(curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/getUpdates")
          echo "Telegram Response: $RESPONSE"
          echo "$RESPONSE" | grep "Test User" || (echo "Test failed!" && exit 1)

      - name: Stop and Remove Containers
        run: docker-compose down

      - name: Push Bot Image
        if: success()
        run: |
          docker tag electro_bot:test $DOCKER_USERNAME/electro_bot:latest
          docker push $DOCKER_USERNAME/electro_bot:latest

      - name: Create GitHub Release for Bot
        uses: softprops/action-gh-release@v1
        with:
          tag_name: bot-v1.0.${{ github.run_number }}
          name: Bot Release v1.0.${{ github.run_number }}
          body: "Автоматически созданный релиз для Бота."
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
