name: Bot Docker Build & Push

on:
  push:
    branches:
      - tg_bot  # Только для изменений в боте

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Bot Docker Image
        run: |
          docker build -t $DOCKER_USERNAME/electro_bot:latest -f bot/Dockerfile ./bot
          docker push $DOCKER_USERNAME/electro_bot:latest
