name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Замените на нужную ветку

permissions:
  contents: write

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t your-image-name:latest .
          docker tag your-image-name:latest $DOCKER_USERNAME/your-image-name:latest

      - name: Push Docker Image
        run: docker push $DOCKER_USERNAME/your-image-name:latest

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          name: "Release v1.0.${{ github.run_number }}"
          body: "Автоматически созданный релиз"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
